name: simple_lead_crm
description: A simple lead CRM for real estate with Firebase backend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_messaging: ^14.7.5

  # State Management
  flutter_riverpod: ^2.4.0

  # UI & Utils
  intl: ^0.19.0
  go_router: ^13.2.2
  flutter_screenutil: ^5.8.4
  url_launcher: ^6.2.5

  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true


  assets:
    - assets/images/