// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg366X9mUZQ5k-aEK-1h43LVg-x5Xssc4',
    appId: '1:586591854546:web:your_web_app_id',
    messagingSenderId: '586591854546',
    projectId: 'boringcrm-6418a',
    authDomain: 'boringcrm-6418a.firebaseapp.com',
    storageBucket: 'boringcrm-6418a.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg366X9mUZQ5k-aEK-1h43LVg-x5Xssc4',
    appId: '1:586591854546:android:d4dd4aee1fcfa5834a720b',
    messagingSenderId: '586591854546',
    projectId: 'boringcrm-6418a',
    storageBucket: 'boringcrm-6418a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg366X9mUZQ5k-aEK-1h43LVg-x5Xssc4',
    appId: '1:586591854546:ios:your_ios_app_id',
    messagingSenderId: '586591854546',
    projectId: 'boringcrm-6418a',
    storageBucket: 'boringcrm-6418a.firebasestorage.app',
    iosBundleId: 'com.example.broingcrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg366X9mUZQ5k-aEK-1h43LVg-x5Xssc4',
    appId: '1:586591854546:ios:your_ios_app_id',
    messagingSenderId: '586591854546',
    projectId: 'boringcrm-6418a',
    storageBucket: 'boringcrm-6418a.firebasestorage.app',
    iosBundleId: 'com.example.broingcrm',
  );
}